# Generated by Django 5.1.1 on 2024-10-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='related_name',
            new_name='project',
        ),
    ]
